apiVersion: batch/v1
kind: Job
metadata:
  name: confeitaria-db-migration
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: ghcr.io/igorbatistadev/confeitaria-backend-devops:ab18dd9531678418461486ff293740e965eb9991
          command: ["/bin/sh", "-c", "seu-comando-de-migration"]
      restartPolicy: OnFailure
